### ISSUE TITLE
Cannot redeploy with the arm or bicep scripts

### ISSUE THREAD

**Issue by kamoclav** [ToddM2/fhir-proxy-deploy#2]
Redeploying using the script does not work as azure keyvault considers the unique value chosen by the script as taken

{
    "status": "Failed",
    "error": {
        "code": "ConflictError",
        "message": "Exist soft deleted vault with the same name. "
    }
}

This line will need some other random element

@description('Unique string that will be used to generate resource names, defaults to the uniqueString function')param uniqueValue string = take(uniqueString(subscription().subscriptionId,resourceGroup().name), 8)

**Comment by ToddM2** [comment]
@kamoclav  - This is the way Azure Key Vault works. It is a resource that should not be deleted  (if you plan to redeploy) or you have to specify a unique key vault name in the parameters file each time. Azure KV holds on to the resource as a protective measure for 7-90 days and the template defaults to 30 days.
